//pub const ID_CUTOFF: f64 = 0.999;
pub const FORWARD_READ_SAFE_SEARCH_CUTOFF: usize = 10000;
//foward_read_safe_search_cutoff: usize = 10000;
pub const MAX_GAP_CHAINING: usize = 200;
pub const SAMPLING_RATE_COV: usize = 10;
pub const MINIMIZER_END_NTH_COV: usize = 20;
pub const QUANTILE_UNITIG_WEIGHT: f64 = 0.50;
pub const MID_BASE_THRESHOLD_READ: u8 = 17; // 98%
pub const MID_BASE_THRESHOLD_INITIAL: u8 = 10; // 90%
pub const MAX_BUBBLE_UNITIGS_FINAL_STAGE: usize = 5;
pub const TS_DASHES_BLANK_COLONS_DOT_BLANK: &str = "%Y-%m-%d %H:%M:%S%.3f";
pub const MIN_CHAIN_SCORE_COMPARE: i32 = 50;
pub const MIN_READ_LENGTH: usize = 1000;
pub const ENDPOINT_MAPPING_FUZZ : u32 = 200;
